name: Issue workflow

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook with full event payload
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          echo "${{ toJSON(github.event) }}" > event.json
          curl -X POST -H "Content-Type: application/json" -d @event.json $WEBHOOK_URL
